title: Purnima Singh
#logo:assests/img/headshot_circle.png
#description:Data Analytics | Data Visualization | Project Management | Business Analysis|SQL
#show_downloads:true
theme: jekyll-theme-minimal
